### ISSUE TITLE
感觉可以开一个 discussions ，这样就可以讨论了

### ISSUE THREAD

**Issue by Alafun** [sanbuphy/-statistics-#4]

**Comment by sanbuphy** [comment]
这个应当如何开呢

**Comment by Alafun** [comment]
> 如何开

hold on..

**Comment by Alafun** [comment]
![image](https://user-images.githubusercontent.com/78416589/155714640-094bb762-29e7-4131-8706-09a03f05c223.png)

**Comment by sanbuphy** [comment]
学会了 谢谢
